"""Create tables

Revision ID: 984ef38e20a4
Revises: b12380a3a67f
Create Date: 2023-07-04 22:19:49.629749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984ef38e20a4'
down_revision = 'b12380a3a67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exploit', sa.String(length=100), nullable=True))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('exploit')

    # ### end Alembic commands ###
